### ISSUE TITLE
data preparation

### ISSUE THREAD

**Issue by FizrukBet** [3dcitydb/webclient#1]
Hello, thanks for your work! I look for the best way to display CityGML data (textured buildings) in Cesium.
 I try to use this webclient for display my data. I exported tiled kml from 3DCityDB with 3DCityDB importer/exporter and I can to display it in google earth
![image](https://cloud.githubusercontent.com/assets/10652308/8526767/47bf4dd0-2411-11e5-8e58-e79bbd840efb.png)

But when I try to display my data in 3dcitydb/webclient  I don't see kml data. I see that I have a request from the browser to gltf model. Whether I need to generate these models? Any help will be useful...
kml: https://drive.google.com/open?id=0B88PO_XBwUZIVVl5cTFqVTR1TjQ

**Comment by yaozhihang** [comment]
Hello,

It is currently not possible to use this webclient for visualisation of the Collada file exported by the current Importer-Exporter tool. An extended version of the importer-exporter tool will be uploaded to the github soon (perhaps in 3-4 weeks) as an additional Branch allowing to export the gltf-model, which can be visualized in the webclient directly.

**Comment by FizrukBet** [comment]
Hello, whether there are any news about export gltf-models?

**Comment by yaozhihang** [comment]
Hello,

we are now focusing on the development of the 3dcitydb-web-map. 
https://github.com/3dcitydb/3dcitydb-web-map

The work of gltf-exporter will be continued as soon as we've finished the 3dictydb-web-map.

**Comment by FizrukBet** [comment]
thanks, I will wait
